version: '3'

services:
  studio:
    image: studio:latest
    build:
      context: .
      args:
        - WSS=${WSS}
    ports:
      - "8080:8080"
    volumes:
      - data:/srv/data

volumes:
  data:
