version: '3'

services:
  studio:
    build:
      context: .
      args:
        - WSS=${WSS}
    ports:
      - "8080:8080"
    volumes:
      - data:/srv/data
    networks:
      - caddy_default

volumes:
  data:
    driver: anybox/buttervolume:latest

networks:
  caddy_default:
    external: true

